apiVersion: rbac.authorization.k8s.io/v1 # Api version for RBAC
kind: Role
metadata:
  name: pod-reader # Name of the role
  namespace: dev # Namespace where the role is applied to
rules:
- apiGroups: [""] # Indicates the API group(Here it indicates core group that is where pod is defined)
  # The empty string indicates the core API group
  resources: ["pods"] # Resources that the role can access
  verbs: ["get", "watch", "list"] # Action it can perform
