apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: backend # Namespace where the role is applied to
  name: secret-admin # Name of the role
rules:
- apiGroups: [""] # Core api group
  resources: ["secrets"] # Resources the role can access
  verbs: ["*"] # Inside secrets it can perfrom all the operations
