apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-view
  namespace: testing
subjects:
- kind: User
  name: bob
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
