apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: alice-pod-reader # Name of the rolebinding resource
  namespace: dev # Namespace where the rolebinding is created
subjects:
- kind: Group
  name: dev-team
roleRef:
  kind: Role
  name: configmap-editor
  apiGroup: rbac.authorization.k8s.io
