apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: alice-pod-reader # Name of the rolebinding resource
  namespace: dev # Namespace where the rolebinding is created
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: dev
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
